language: cpp

before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo add-apt-repository ppa:boost-latest/ppa -y
    - sudo apt-get update -qq
    - export CC=${REAL_CC} CXX=${REAL_CXX}

install:
    - sudo apt-get install cmake
    - sudo apt-get install -qq g++-4.8
    - sudo apt-get install libssl-dev
    - sudo apt-get install ragel
    - sudo apt-get install libjansson-dev
    - sudo apt-get install libc-ares-dev
    - sudo apt-get install libboost1.54-all-dev

env:
    - ignore=this

matrix:
    exclude:
        - env: ignore=this
    include:
        - compiler: gcc
        - env: REAL_CC=gcc-4.8 REAL_CXX=g++-4.8

script:
    - mkdir b
    - cd b
    - cmake ..
    - make

after_script:
    - make test
